# Image directory (default: images)
image_dir: assets/images

sidebar:
    menu:
        home:
            title: Home
            url: /
            icon: home
#        categories:
#            title: Categories
#            url: /all-categories
#            icon: bookmark
        tags:
            title: Tags
            url: /all-tags
            icon: tags
        archives:
            title: Archives
            url: /all-archives
            icon: archive
#        search:
#            title: Search
#            url: /#search
#            icon: search
#            # `st-search-show-outputs` classes are used to open swiftype search window
#            class: st-search-show-outputs
        about:
            title: About me
            url: /#about
            icon: question
    author_links:
         github:
             title: GitHub
             url: https://github.com/bcokert
             icon: github
#         stack_overflow:
#             title: Stack Overflow
#             url: http://stackoverflow.com/users/bcokert
#             icon: stack-overflow
         twitter:
             title: Twitter
             url: https://twitter.com/BrandonOkert
             icon: twitter
#         facebook:
#             title: Facebook
#             url: https://www.facebook.com/
#             icon: facebook
#         google_plus:
#             title: Google +
#             url: https://plus.google.com/
#             icon: google-plus
         linked_in:
             title: Linked In
             url: https://www.linkedin.com/pub/brandon-okert/32/aa6/850
             icon: linkedin
#         mail:
#             title: Mail
#             url: mailto:
#             icon: envelope-o
#    rss:
#        rss:
#            title: RSS
#            url: /atom.xml
#            icon: rss

# Header configuration
# The link at the right of the header is customizable
# You can add a link (as an icon) at the right of the header instead of the author's gravatar image or author's picture.
# DON'T edit `header`, `right_link`, `url`, `icon` and `class` variable name
header:
    right_link:
         url: /#search
         icon: search
         class: st-search-show-outputs

# Author
author:
    name: Brandon Okert
    email: bcokert@gmail.com
    # Your biography (Markdown and HTML supported)
    bio: |
      Husband, Software Engineer, Web Developer, Coffee Geek, Chess Dabbler, Runner, Strategy Gamer, Dog Owner, Cat Lover.
      ![](/img/about/about-me-profile.jpg) ![](/img/about/sarah3.png) ![](/img/about/storm-n-me.jpg) ![](/img/about/storm-giving-a-speech.jpg)
      ![](/img/about/brandonsarah1.jpg) ![](/img/about/brandonsarah2.jpg) ![](/img/about/sarah1.jpg) ![](/img/about/sarah2.jpg)
    job: Hootsuite Media Inc.
    location: Vancouver, BC
    # Your profile picture located in folder `source/_images/` (development)
    # or in `source/assets/images/` (production).
    # Overwritten by your gravatar image if `gravatar_image` is enabled
    picture:
    # Your Twitter username without the @. E.g : `tranquilpeak`
    twitter: BrandonOkert
    # Your google plus profile id. E.g : `+Tranquilpeak` or `123812884128439`
    google_plus:


# Customization
# Define the behavior of the sidebar
# 1: Display large sidebar on large screen, medium sidebar on medium screen and header bar on small screen
# and large sidebar is swiped (default)
# 2: Display medium sidebar on large and medium screen and header bar on small screen and medium sidebar is swiped
# 3: Display header bar on all screens and large sidebar is swiped
# 4: Display header bar on all screens and medium sidebar is swiped
sidebar_behavior: 1
# Head title displayed at the top of the table of contents.
toc_title: Contents
# Display thumbnail image of each post on index pages (false: disabled, true: enabled)
thumbnail_image: true
# Message displayed after the <!-- more --> comment
read_more_message: Continue reading
# Message displayed after the <!-- more --> comment or after 300 characters for post with link layout
go_to_message:   Go to the website
# Your blog cover picture located in folder `source/_images/` (development) or in `source/assets/images/` (production)
cover_image: covercloud.png
# Your favicon located in folder `source/_images/` (development) or in `source/assets/images/` (production)
favicon:
# Display an image gallery at the end of a post which have photos variables (false: disabled, true: enabled)
image_gallery: true
# Pagination behavior of archive, category and tag pages (false: pagination disabled, true: pagination enabled)
archive_pagination: true
category_pagination: true
tag_pagination: true

# Integrated services
# Your Disqus shortname
disqus_shortname: brandonokert
# Your Google analystics web property ID : UA-XXXXX-X
google_analytics_id:
# Your Gravatar email. Overwrite `author.picture` everywhere in the blog
gravatar_email: bcokert@gmail.com
# Your swiftype install key
swiftype_install_key:
# Your Facebook user ids used to connect your blog with your facebook user accounts (Facebook Insights). Separate ids with comma. e.g : 9830047,1003342
fb_admin_ids:
# Your Facebook app id used to connect your blog with your facebook app account (Facebook Insights). E.g : 9841307
fb_app_id:
